version: 2.1

orbs:
  node: circleci/node@5.1.0
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  test:
    docker:
      - image: cimg/node:18.19-browsers
    steps:
      - checkout
      
      # Install Chrome
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      
      # Set Chrome binary path
      - run:
          name: Setup Chrome Environment
          command: |
            echo 'export CHROME_BIN=/usr/bin/google-chrome' >> $BASH_ENV
            source $BASH_ENV
      
      # Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      
      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      
      # Cache dependencies for future runs
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      # Run tests
      - run:
          name: Run Tests
          command: yarn test
      
      # Store test results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test