version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  test:
    docker:
      - image: cimg/node:18.19-browsers
    steps:
      - checkout
      
      # Restore cached dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      
      # Install dependencies
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      
      # Cache dependencies for future runs
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      
      # Run tests
      - run:
          name: Run Tests
          command: yarn test
      
      # Store test results
      - store_test_results:
          path: test-results

workflows:
  version: 2
  test:
    jobs:
      - test